// Generated by CoffeeScript 1.7.1
(function() {
  var limit, munchhausen;

  limit = 100000;

  munchhausen = function() {
    var arr, i, j, total, _i, _j, _len, _results;
    _results = [];
    for (i = _i = 0; 0 <= limit ? _i < limit : _i > limit; i = 0 <= limit ? ++_i : --_i) {
      arr = i.toString().split('');
      total = 0;
      for (_j = 0, _len = arr.length; _j < _len; _j++) {
        j = arr[_j];
        total = total + Math.pow(j, j);
      }
      if (total.toString() === i.toString()) {
        _results.push(console.log(i + ' is a Munchasen'));
      } else {
        _results.push(void 0);
      }
    }
    return _results;
  };

  munchhausen();

}).call(this);

//# sourceMappingURL=münchausenCoffee.map
